#!/usr/bin/env node
// Assembles a minimal Godot project from `reference/godot/`, so the parity-trace
// exporter can run in CI without a checkout of SwingBy2026.
//
// Why this is legitimate rather than a shortcut: `tools/godot-trace/trace.gd`
// needs exactly three things — the `PhysicsEngine` and `GameConstants` classes,
// and `res://data/levels_builtin.json`. Both scripts are dependency-free
// `class_name` globals (verified: neither references DataManager, AudioManager,
// SceneController or GameWorld, and neither preloads anything), and all three
// files are already committed under `reference/` as a verbatim snapshot of
// SwingBy2026 at dd2b501 — checked in precisely so agents in isolated containers
// can read them. Running a REAL Godot binary over that REAL GDScript is what the
// parity traces are for.
//
// The one thing this does NOT give you: traces that track SwingBy2026's HEAD. It
// pins to the committed snapshot. If the Godot original moves, refresh
// `reference/godot/` first — that is a deliberate update, not something CI should
// do silently behind your back.
//
// `reference/` is read-only (reference/README.md), so nothing is written there;
// the assembled project goes to a scratch directory.
//
// Usage: node infra/godot-project.mjs [outDir]   (default: .godot-parity-project)

import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  existsSync,
} from "node:fs";
import path from "node:path";

const OUT = path.resolve(process.argv[2] || ".godot-parity-project");
const REF = path.resolve("reference/godot");

const NEEDED_SCRIPTS = ["PhysicsEngine.gd", "GameConstants.gd"];
const LEVELS = "levels_builtin.json";

function fail(msg) {
  console.error(`godot-project: ${msg}`);
  process.exit(1);
}

if (!existsSync(REF)) fail(`${REF} not found — run from the repo root`);

mkdirSync(path.join(OUT, "scripts"), { recursive: true });
mkdirSync(path.join(OUT, "data"), { recursive: true });

for (const name of NEEDED_SCRIPTS) {
  const src = path.join(REF, "scripts", name);
  if (!existsSync(src)) fail(`missing ${src}`);
  copyFileSync(src, path.join(OUT, "scripts", name));
}

const levelsSrc = path.join(REF, "data", LEVELS);
if (!existsSync(levelsSrc)) fail(`missing ${levelsSrc}`);
copyFileSync(levelsSrc, path.join(OUT, "data", LEVELS));

// Godot 4 project file. `config_version=5` is Godot 4.x. No autoloads, no main
// scene: trace.gd `extends SceneTree` and is run with --script, so nothing else
// needs to exist. class_name registration happens on project scan.
writeFileSync(
  path.join(OUT, "project.godot"),
  `; Generated by infra/godot-project.mjs — do not edit, do not commit.
; Minimal project wrapping reference/godot/ so tools/godot-trace/trace.gd can run
; headless in CI. See that script's header for the invocation.

config_version=5

[application]

config/name="SwingBy parity harness"
config/features=PackedStringArray("4.3")

[rendering]

renderer/rendering_method="gl_compatibility"
`,
);

const copied = [
  ...NEEDED_SCRIPTS.map((n) => `scripts/${n}`),
  `data/${LEVELS}`,
  "project.godot",
];
console.log(`assembled Godot project at ${OUT}`);
for (const f of copied) console.log(`  ${f}`);

// Sanity: the two scripts must still declare their class_name, or trace.gd's
// `PhysicsEngine.substep_count(...)` calls resolve to nothing.
for (const name of NEEDED_SCRIPTS) {
  const body = readFileSync(path.join(OUT, "scripts", name), "utf8");
  const expected = name.replace(/\.gd$/, "");
  if (!new RegExp(`^class_name\\s+${expected}\\b`, "m").test(body)) {
    fail(
      `${name} no longer declares 'class_name ${expected}' — trace.gd would fail to resolve it`,
    );
  }
}
console.log("verified: both scripts declare their class_name");
